DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Groupss;
DROP TABLE IF EXISTS Rooms;
DROP TABLE IF EXISTS UsersGroups;
DROP TABLE IF EXISTS GroupsRooms;
DROP TABLE IF EXISTS UsersGroupsRooms;
CREATE TABLE Users ( UserId int PRIMARY KEY, UserName varchar (30) Not NULL);
INSERT INTO Users ( UserId, UserName ) VALUES (1, 'Modesto');
INSERT INTO Users ( UserId, UserName ) VALUES (2, 'Ayine');
INSERT INTO Users ( UserId, UserName ) VALUES (3, 'Christopher');
INSERT INTO Users ( UserId, UserName ) VALUES (4, 'Cheong');
INSERT INTO Users ( UserId, UserName ) VALUES (5, 'Saulat');
INSERT INTO Users ( UserId, UserName ) VALUES (6, 'Heidy');
SELECT * FROM Users;
CREATE TABLE Rooms ( RoomId int PRIMARY KEY, RoomName varchar (30) NOT NULL );
INSERT INTO Rooms ( RoomId, RoomName ) VALUES ( 101,'101');
INSERT INTO Rooms ( RoomId, RoomName ) VALUES ( 102,'102');
INSERT INTO Rooms ( RoomId, RoomName ) VALUES ( 103,'Auditorium A');
INSERT INTO Rooms ( RoomId, RoomName ) VALUES ( 104,'Auditorium B');
SELECT * FROM Rooms;
CREATE TABLE UsersGroups( UgId int PRIMARY KEY, UserId int NOT NULL, GrampId int NOT NULL );
INSERT INTO UsersGroups ( UgId, UserId, GroupId ) VALUES ( 121, 1, 21) ;
INSERT INTO UsersGroups ( UgId, UserId, GroupId ) VALUES ( 122, 2, 21) ;
INSERT INTO UsersGroups ( UgId, UserId, GroupId ) VALUES ( 123, 3, 22) ;
INSERT INTO UsersGroups ( UgId, UserId, GroupId ) VALUES ( 124, 4, 22) ;
SELECT * FROM UsersGroups;
CREATE TABLE GroupsRooms ( GrId int PRIMARY KEY, GroupId int NOT NULL, RoomId int NOT NULL );
INSERT INTO GroupsRooms ( GrId, GroupId, RoomId ) VALUES ( 1101, 21, 101) ;
INSERT INTO GroupsRooms ( GrId, GroupId, RoomId ) VALUES ( 1102, 21, 102) ;
INSERT INTO GroupsRooms ( GrId, GroupId, RoomId ) VALUES ( 1103, 22, 102) ;
INSERT INTO GroupsRooms ( GrId, GroupId, RoomId ) VALUES ( 1104, 22, 103) ;
SELECT * FROM GroupsRomms;
CREATE TABLE GroupsRooms ( UgrId int PRIMARY KEY, GroupId int NOT NULL,
RoomId int NOT NULL );
INSERT INTO UsersGroupsRooms ( UgrId, UserId, GroupId, RoomId ) VALUES ( 2101, 1, 21, 101) ;
INSERT INTO UsersGroupsRooms ( UgrId, UserId, GroupId, RoomId ) VALUES ( 2102, 2, 21, 102) ;
INSERT INTO UsersGroupsRooms ( UgrId, UserId, GroupId, RoomId ) VALUES ( 2103, 3, 22, 102 );
INSERT INTO UsersGroupsRooms ( UgrId, UserId, GroupId, RoomId ) VALUES ( 2104, 4, 22, 103) ;
